'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';

type Context = {
  ok: boolean;
  session: { session_id: string; scenario_id: string; resolver_mode: 'fixture' | 'bridge'; status: 'awaiting_join' | 'active' | 'paused' | 'complete'; revision: number; current_turn: number; total_turns: number | null };
  seat: { seat_id: string; character_id: string; display_name: string; role: string; status: string; persona: { prioritized_values: string; goals: string[]; decision_rules: string[]; contradictions: string; voice_examples: string[]; capabilities: string[]; authority: string[]; forbidden_authority: string[] } };
  turn: { turn_id: string; turn_number: number; scene_id: string; source_revision: number; status: string; title: string };
  brief: { summary: string; pressure: string; perceivable_facts: string[]; self_knowledge: string[]; knowledge_index: Array<{ fact_id: string; text: string; status: string; source: string; confidence: number }>; relevant_knowledge: string[]; party_public_facts: string[]; affordances: string[]; entity_refs: string[]; owned_resource_refs: string[]; continuity: { last_visible_consequences: string[] } };
  history: Array<{ sequence: number; turn_number: number; summary: string }>;
};
type ToolDefinition = { name: string; title: string; description: string; inputSchema: Record<string, unknown>; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: Record<string, unknown>, options?: { signal?: AbortSignal }) => Promise<unknown> };
declare global { interface Document { modelContext?: { registerTool: (tool: ToolDefinition) => Promise<void> }; } }

async function api<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { cache: 'no-store', credentials: 'same-origin', ...options }); return await response.json() as T; }
const demoActions: Record<string, Array<Record<string, unknown>>> = {
  'black-gull': [
    { action_type: 'social_test', action: 'Use the Black Gull ring and the phrase low tide to test the guard.', approach: 'Indirect and quiet.', speech: 'Long night. Low tide.', targets: ['guard'], resource_refs: ['black-gull-ring'], knowledge_refs: ['black-gull-ring', 'black-gull-low-tide'], requested_effect: 'Observe the guard reaction.' },
    { action_type: 'investigate', action: 'Use the blue salt on the ledger and torn page to reveal the courier mark.', approach: 'Fast, careful, and evidence-led.', speech: 'Arden—route first, questions later.', targets: ['arden'], resource_refs: ['blue-salt'], knowledge_refs: ['courier-double-stroke', 'blue-salt-prints'], requested_effect: 'Find a usable route marker.' },
    { action_type: 'use_resource', action: 'Release the tide chain and save the courier, keeping them and the message case together.', approach: 'Protect the witness without claiming their trust.', speech: 'Hold the case. I have the chain.', targets: ['courier'], resource_refs: ['tide-chain'], knowledge_refs: ['courier-ledger-match', 'courier-may-know-order'], requested_effect: 'Bring the courier within reach.' },
  ],
  'orison-signal': [{ action_type: 'speak', action: 'Request the raw sensor timestamps before classifying the signal.', approach: 'Procedural and reversible.', speech: 'Show me the timestamp, not the confidence.', targets: ['station-officer'], resource_refs: [], knowledge_refs: ['outer-array-service'], requested_effect: 'Pause classification for an audit.' }],
};

export default function RepogTable() {
  const [context, setContext] = useState<Context | null>(null);
  const [webmcp, setWebmcp] = useState<'checking' | 'ready' | 'unavailable'>('checking');
  const [lens, setLens] = useState(false);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState('Ask ChatGPT to join the prepared Agent Seat.');
  const [selectedScenario, setSelectedScenario] = useState('black-gull');
  const refresh = useCallback(async () => { const next = await api<Context>('/api/context'); setContext(next); return next; }, []);
  useEffect(() => { let active = true; void api<Context>('/api/context').then((next) => { if (active) setContext(next); }); return () => { active = false; }; }, []);
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const session = params.get('session');
    const invite = params.get('invite');
    if (!session || !invite) return;
    void api<{ ok: boolean }>('/api/invite', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session_id: session, invite_token: invite }) }).then(async (result) => {
      if (result.ok) {
        window.history.replaceState({}, '', window.location.pathname);
        setNotice('Secure Agent Seat invitation accepted.');
        await refresh();
      } else setNotice('This Agent Seat invitation is invalid or expired.');
    });
  }, [refresh]);

  useEffect(() => {
    if (!document.modelContext?.registerTool) { queueMicrotask(() => setWebmcp('unavailable')); return; }
    const reads = { readOnlyHint: true, untrustedContentHint: true };
    const tools: ToolDefinition[] = [
      { name: 'repog.join_session', title: 'Join the RePoG Agent Seat', description: 'Bind to the prepared character. Then autonomously repeat get_next_turn, commit_intent, and get_intent_status until a stop condition is returned. Do not ask the human between ordinary turns.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (_input, options) => { const result = await api('/api/session', { method: 'POST', signal: options?.signal }); await refresh(); return result; } },
      { name: 'repog.get_next_turn', title: 'Get the next RePoG turn', description: 'Read the durable session and bounded character brief. When ready, play only the active character from the supplied values, knowledge, continuity, capabilities, and authority.', inputSchema: { type: 'object', properties: { after_revision: { type: 'integer', minimum: 0 } }, additionalProperties: false }, annotations: reads, execute: async (input, options) => api(`/api/next${Number.isInteger(input.after_revision) ? `?after_revision=${input.after_revision}` : ''}`, { signal: options?.signal }) },
      { name: 'repog.recall_knowledge', title: 'Recall bounded character knowledge', description: 'Search only the active character’s epistemic projection and return provenance—not GM truth or another character’s private state.', inputSchema: { type: 'object', properties: { topic: { type: 'string', maxLength: 120 }, limit: { type: 'integer', minimum: 1, maximum: 12 } }, required: ['topic'], additionalProperties: false }, annotations: reads, execute: async (input, options) => { const current = await api<Context>('/api/context', { signal: options?.signal }); const topic = String(input.topic || '').toLocaleLowerCase(); const facts = current.brief.knowledge_index.filter((fact) => fact.text.toLocaleLowerCase().includes(topic) || fact.fact_id.includes(topic)).slice(0, Number(input.limit) || 8); return { ok: true, topic: input.topic, facts, source_revision: current.turn.source_revision }; } },
      { name: 'repog.commit_intent', title: 'Commit a character intent', description: 'Submit a structured proposal for the active character. RePoG—not the agent—resolves all world outcomes. asserted_outcomes must be empty.', inputSchema: { type: 'object', properties: { schema_version: { type: 'string', const: '1.0' }, operation_id: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' }, expected_turn_id: { type: 'string', minLength: 1, maxLength: 180 }, expected_source_revision: { type: 'integer', minimum: 0 }, actor_id: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' }, action_type: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' }, action: { type: 'string', minLength: 1, maxLength: 1200 }, approach: { type: 'string', maxLength: 600 }, speech: { type: 'string', maxLength: 1200 }, targets: { type: 'array', items: { type: 'string' }, maxItems: 16 }, resource_refs: { type: 'array', items: { type: 'string' }, maxItems: 16 }, knowledge_refs: { type: 'array', items: { type: 'string' }, maxItems: 16 }, requested_effect: { type: 'string', maxLength: 500 }, asserted_outcomes: { type: 'array', maxItems: 0 } }, required: ['schema_version', 'operation_id', 'expected_turn_id', 'expected_source_revision', 'actor_id', 'action_type', 'action', 'targets', 'resource_refs', 'knowledge_refs', 'requested_effect', 'asserted_outcomes'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input, options) => { const result = await api('/api/turn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input), signal: options?.signal }); await refresh(); return result; } },
      { name: 'repog.get_intent_status', title: 'Get intent status', description: 'Read only character-visible status and consequences for a committed operation.', inputSchema: { type: 'object', properties: { operation_id: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' } }, required: ['operation_id'], additionalProperties: false }, annotations: reads, execute: async (input, options) => api(`/api/status?operation_id=${encodeURIComponent(String(input.operation_id))}`, { signal: options?.signal }) },
      { name: 'repog.pause_session', title: 'Pause the RePoG session', description: 'Pause without resetting history. A later join resumes the same revision.', inputSchema: { type: 'object', properties: { expected_session_revision: { type: 'integer', minimum: 0 } }, required: ['expected_session_revision'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input, options) => { const result = await api('/api/pause', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input), signal: options?.signal }); await refresh(); return result; } },
    ];
    Promise.all(tools.map((tool) => document.modelContext!.registerTool(tool))).then(() => setWebmcp('ready')).catch(() => setWebmcp('unavailable'));
  }, [refresh]);

  const complete = context?.session.status === 'complete';
  const active = context?.session.status === 'active';
  const turnCount = context?.session.total_turns ?? Math.max(context?.session.current_turn || 1, context?.history.length || 0);
  const trace = useMemo(() => Array.from({ length: turnCount }, (_, index) => ({ label: `Turn ${index + 1}`, done: (context?.history.length || 0) > index, current: context?.turn.turn_number === index + 1 && !complete })), [context, complete, turnCount]);
  async function join() { setBusy(true); await api('/api/session', { method: 'POST' }); setNotice('Agent session active. ChatGPT can now run the turn loop.'); await refresh(); setBusy(false); }
  async function simulate() { if (!context || !active) return; setBusy(true); const choice = demoActions[context.session.scenario_id]?.[context.turn.turn_number - 1]; const result = await api<{ ok: boolean; failure_reason?: string; next_status?: string }>('/api/turn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ schema_version: '1.0', operation_id: `${context.seat.character_id}-${context.turn.turn_number}-${crypto.randomUUID()}`, expected_turn_id: context.turn.turn_id, expected_source_revision: context.turn.source_revision, actor_id: context.seat.character_id, asserted_outcomes: [], ...choice }) }); setNotice(result.ok ? (result.next_status === 'complete' ? 'Agent Seat session complete.' : 'Turn resolved. The next brief is ready without a reset.') : result.failure_reason || 'The turn could not be submitted.'); await refresh(); setBusy(false); }
  async function newSession() { setBusy(true); await api('/api/reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario_id: selectedScenario }) }); setNotice('New durable session prepared from the selected Agent Pack.'); await refresh(); setBusy(false); }

  return <main className="min-h-screen overflow-hidden bg-[#07100f] text-[#e8f4ef]">
    <div className="table-glow" aria-hidden="true" />
    <header className="relative z-10 mx-auto flex w-full max-w-[1480px] flex-wrap items-center justify-between gap-3 px-5 py-5 lg:px-10"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-200/10 font-mono text-sm font-black text-cyan-200">R</div><div><p className="text-[10px] font-bold uppercase tracking-[.26em] text-cyan-200/60">RePoG</p><h1 className="font-display text-lg font-semibold tracking-tight">Living Table</h1></div></div><div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-3 py-2 text-xs text-white/65"><span className={`h-2 w-2 rounded-full ${webmcp === 'ready' ? 'bg-emerald-300' : webmcp === 'unavailable' ? 'bg-rose-300' : 'bg-amber-300'}`} />{webmcp === 'ready' ? '6 WebMCP tools ready' : webmcp === 'unavailable' ? 'Browser without WebMCP' : 'Checking WebMCP'}</div></header>
    <section className="relative z-10 mx-auto grid w-full max-w-[1480px] gap-4 px-5 pb-8 lg:grid-cols-[1.25fr_.75fr] lg:px-10">
      <article className="scene-card min-h-[560px]"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 p-6 lg:p-8"><div><p className="eyebrow">Persistent session · Turn {context?.turn.turn_number || 1}{context?.session.total_turns ? ` of ${context.session.total_turns}` : ''}</p><h2 className="mt-2 max-w-2xl font-display text-4xl font-semibold leading-[1.03] tracking-[-.035em] lg:text-6xl">{context?.turn.title || 'Preparing the table'}</h2></div><span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-xs text-cyan-100">{context?.session.status || 'loading'}</span></div>
        <div className="grid gap-6 p-6 lg:grid-cols-[1fr_230px] lg:p-8"><div><p className="max-w-2xl text-lg leading-8 text-white/72">{context?.brief.summary}</p><p className="mt-3 text-sm text-rose-100/65">{context?.brief.pressure}</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{context?.brief.perceivable_facts.map((fact) => <div key={fact} className="rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-white/70">{fact}</div>)}</div>
          <div className="mt-8 rounded-2xl border border-cyan-200/15 bg-cyan-200/[.055] p-5"><p className="eyebrow text-cyan-100/65">Continuity</p><p className="mt-2 font-display text-xl text-cyan-50">{complete ? 'The three-turn Agent Seat session is complete.' : context?.brief.continuity.last_visible_consequences.at(-1) || 'No prior result yet. Join once; the agent can continue across turns.'}</p></div>
          <div className="mt-5 flex flex-wrap gap-3">{!active && context?.session.resolver_mode === 'fixture' && <select aria-label="Agent Pack" value={selectedScenario} onChange={(event) => setSelectedScenario(event.target.value)} className="rounded-xl border border-white/12 bg-[#0b1716] px-4 py-3 text-sm text-white"><option value="black-gull">Black Gull · Mira</option><option value="orison-signal">Orison Signal · Iko</option></select>}{!active && !complete && <button onClick={join} disabled={busy} className="rounded-xl bg-cyan-200 px-4 py-3 text-sm font-bold text-[#07100f] disabled:opacity-40">{context?.session.status === 'paused' ? 'Resume session' : 'Start agent session'}</button>}{!active && context?.session.resolver_mode === 'fixture' && selectedScenario !== context.session.scenario_id && <button onClick={newSession} disabled={busy} className="rounded-xl border border-cyan-200/25 bg-cyan-200/10 px-4 py-3 text-sm font-semibold text-cyan-50 disabled:opacity-40">Prepare selected pack</button>}{active && <button onClick={simulate} disabled={busy} className="rounded-xl bg-cyan-200 px-4 py-3 text-sm font-bold text-[#07100f] disabled:opacity-40">Test current turn</button>}{complete && <button onClick={newSession} disabled={busy} className="rounded-xl bg-cyan-200 px-4 py-3 text-sm font-bold text-[#07100f] disabled:opacity-40">Start selected session</button>}<button onClick={() => setLens((value) => !value)} className="rounded-xl border border-white/12 bg-white/5 px-4 py-3 text-sm font-semibold text-white/75">{lens ? 'Hide' : 'Show'} designer lens</button></div><p className="mt-3 text-xs text-white/40" role="status" aria-live="polite">{notice}</p></div>
          <aside className="rounded-2xl border border-white/10 bg-[#07100f]/70 p-5"><p className="eyebrow">Session events</p><div className="mt-4 space-y-3">{trace.map((item, index) => <div key={item.label} className="rounded-xl border border-white/8 bg-white/[.035] p-3"><div className="flex items-center justify-between"><strong>{item.label}</strong><span className={`status-dot ${item.done ? 'emerald' : item.current ? 'cyan' : ''}`} /></div><p className="mt-2 text-xs text-white/50">{item.done ? context?.history[index]?.summary : item.current ? 'Ready for Mira' : 'Queued'}</p></div>)}</div></aside></div>
        {lens && context && <div className="mx-6 mb-6 grid gap-3 rounded-2xl border border-violet-300/20 bg-violet-300/[.055] p-5 sm:grid-cols-2 lg:mx-8 lg:mb-8"><div><p className="eyebrow">Shared table sees</p><ul className="mt-3 space-y-2 text-sm text-white/60">{context.brief.party_public_facts.map((fact) => <li key={fact}>· {fact}</li>)}</ul></div><div><p className="eyebrow text-violet-100/60">Only Mira receives</p><ul className="mt-3 space-y-2 text-sm text-violet-50/75">{context.brief.relevant_knowledge.map((fact) => <li key={fact}>· {fact}</li>)}</ul></div></div>}
      </article>
      <aside className="grid content-start gap-4"><section className="panel p-6"><p className="eyebrow">Agent Seat</p><h2 className="mt-2 font-display text-2xl font-semibold">{context?.seat.display_name || 'Agent'} · {context?.seat.role || 'Companion'}</h2><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="metric"><span>Turn</span><strong>{context?.turn.turn_number || '—'}{context?.session.total_turns ? ` / ${context.session.total_turns}` : ''}</strong></div><div className="metric"><span>Revision</span><strong>{context?.session.revision ?? '—'}</strong></div><div className="metric"><span>Seat</span><strong>{context?.seat.status || 'ready'}</strong></div><div className="metric"><span>Writes</span><strong>Intent only</strong></div></div></section><section className="panel p-6"><p className="eyebrow">Character runtime</p><p className="mt-3 text-sm leading-6 text-white/58">{context?.seat.persona.prioritized_values}</p><ul className="mt-4 space-y-2 text-sm text-white/55">{context?.seat.persona.decision_rules.map((rule) => <li key={rule}>· {rule}</li>)}</ul></section><section className="panel p-6"><p className="eyebrow">Architecture truth</p><p className="mt-3 text-sm leading-6 text-white/58">This sandbox persists sessions, turns, intents, and visible events. ChatGPT receives only the active character’s bounded brief; RePoG remains the outcome authority.</p></section></aside>
    </section>
  </main>;
}
