'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Bell, BookOpen, CaretDown, Check, Compass, Crosshair, DoorOpen, Eye, Feather, GearSix, Hand, HourglassHigh, MagnifyingGlass, ShieldChevron, Sparkle, UserCircle, X } from '@phosphor-icons/react';
import { createWebMcpTools, type ToolDefinition } from '@/lib/webmcp-tools';

type Context = {
  ok: boolean;
  session: { session_id: string; scenario_id: string; resolver_mode: 'fixture' | 'bridge' | 'hosted'; status: 'awaiting_join' | 'active' | 'paused' | 'complete'; revision: number; current_turn: number; total_turns: number | null };
  seat: { seat_id: string; character_id: string; display_name: string; role: string; status: string; persona: { prioritized_values: string; goals: string[]; decision_rules: string[]; contradictions: string; voice_examples: string[]; capabilities: string[]; authority: string[]; forbidden_authority: string[] } };
  turn: { turn_id: string; turn_number: number; scene_id: string; source_revision: number; status: string; title: string };
  brief: { summary: string; pressure: string; perceivable_facts: string[]; self_knowledge: string[]; knowledge_index: Array<{ fact_id: string; text: string; status: string; source: string; confidence: number }>; relevant_knowledge: string[]; party_public_facts: string[]; affordances: string[]; entity_refs: string[]; owned_resource_refs: string[]; continuity: { last_visible_consequences: string[] } };
  visual?: { theme_profile: 'fantasy_noir' | 'space_operatic' | 'neutral'; scene_art: { url: string; alt: string; canon_status: 'accepted'; revision: number }; human_seat: { display_name: string; role: string; portrait_url: string; portrait_alt: string }; agent_portrait: { url: string; alt: string; canon_status: 'accepted'; revision: number }; palette: { accent: string; signal: string; atmosphere: string } };
  history: Array<{ sequence: number; turn_number: number; summary: string; visible_consequences?: string[] }>;
};

declare global { interface Document { modelContext?: { registerTool: (tool: ToolDefinition) => Promise<void> }; } }
async function api<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { cache: 'no-store', credentials: 'same-origin', ...options }); return await response.json() as T; }

const demoActions: Record<string, Array<Record<string, unknown>>> = {
  'black-gull': [
    { action_type: 'social_test', action: 'Use the Black Gull ring and the phrase low tide to test the guard.', approach: 'Indirect and quiet.', speech: 'Long night. Low tide.', targets: ['guard'], resource_refs: ['black-gull-ring'], knowledge_refs: ['black-gull-ring', 'black-gull-low-tide'], requested_effect: 'Observe the guard reaction.' },
    { action_type: 'investigate', action: 'Use the blue salt on the ledger and torn page to reveal the courier mark.', approach: 'Fast, careful, and evidence-led.', speech: 'Arden—route first, questions later.', targets: ['arden'], resource_refs: ['blue-salt'], knowledge_refs: ['courier-double-stroke', 'blue-salt-prints'], requested_effect: 'Find a usable route marker.' },
    { action_type: 'use_resource', action: 'Release the tide chain and save the courier, keeping them and the message case together.', approach: 'Protect the witness without claiming their trust.', speech: 'Hold the case. I have the chain.', targets: ['courier'], resource_refs: ['tide-chain'], knowledge_refs: ['courier-ledger-match', 'courier-may-know-order'], requested_effect: 'Bring the courier within reach.' },
  ],
  'orison-signal': [{ action_type: 'speak', action: 'Request the raw sensor timestamps before classifying the signal.', approach: 'Procedural and reversible.', speech: 'Show me the timestamp, not the confidence.', targets: ['station-officer'], resource_refs: [], knowledge_refs: ['outer-array-service'], requested_effect: 'Pause classification for an audit.' }],
};
const factIcons = [Hand, Bell, DoorOpen];

export default function RepogTable() {
  const [context, setContext] = useState<Context | null>(null);
  const [webmcp, setWebmcp] = useState<'checking' | 'ready' | 'unavailable'>('checking');
  const [lens, setLens] = useState(false);
  const [hostedOpen, setHostedOpen] = useState(false);
  const [ledgerTab, setLedgerTab] = useState<'events' | 'thread'>('events');
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState('Ask ChatGPT to join the prepared Agent Seat.');
  const [selectedScenario, setSelectedScenario] = useState('black-gull');
  const [hostedMode, setHostedMode] = useState<'prepared' | 'quick_forge'>('prepared');
  const [forgePrompt, setForgePrompt] = useState('A tense, character-driven fantasy mystery with one Tier 3 companion.');
  const [webmcpOptIn, setWebmcpOptIn] = useState(true);
  const [humanAction, setHumanAction] = useState('');

  const refresh = useCallback(async () => { const next = await api<Context>('/api/context'); setContext(next); setSelectedScenario(next.session.scenario_id in demoActions ? next.session.scenario_id : 'black-gull'); return next; }, []);
  useEffect(() => { let mounted = true; void api<Context>('/api/context').then((next) => { if (mounted) { setContext(next); setSelectedScenario(next.session.scenario_id in demoActions ? next.session.scenario_id : 'black-gull'); } }); return () => { mounted = false; }; }, []);
  useEffect(() => { const params = new URLSearchParams(window.location.search); const session = params.get('session'); const invite = params.get('invite'); if (!session || !invite) return; void api<{ ok: boolean }>('/api/invite', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session_id: session, invite_token: invite }) }).then(async (result) => { if (result.ok) { window.history.replaceState({}, '', window.location.pathname); setNotice('Secure Agent Seat invitation accepted.'); await refresh(); } else setNotice('This Agent Seat invitation is invalid or expired.'); }); }, [refresh]);
  useEffect(() => { if (!document.modelContext?.registerTool) { queueMicrotask(() => setWebmcp('unavailable')); return; } const tools = createWebMcpTools(api, refresh); Promise.all(tools.map((tool) => document.modelContext!.registerTool(tool))).then(() => setWebmcp('ready')).catch(() => setWebmcp('unavailable')); }, [refresh]);

  const complete = context?.session.status === 'complete';
  const active = context?.session.status === 'active';
  const hosted = context?.session.resolver_mode === 'hosted';
  const totalTurns = context?.session.total_turns ?? Math.max(context?.session.current_turn || 1, context?.history.length || 0, 3);
  const visual = context?.visual;
  const theme = visual?.theme_profile || (context?.session.scenario_id === 'orison-signal' ? 'space_operatic' : 'fantasy_noir');
  const latestConsequence = context?.brief.continuity.last_visible_consequences.at(-1);
  const trace = useMemo(() => Array.from({ length: totalTurns }, (_, index) => ({ label: `Turn ${index + 1}`, done: (context?.history.length || 0) > index, current: context?.turn.turn_number === index + 1 && !complete })), [context, complete, totalTurns]);

  async function join() { setBusy(true); await api('/api/session', { method: 'POST' }); setNotice('Agent session active. The shared turn can begin.'); await refresh(); setBusy(false); }
  async function simulate() { if (!context || !active) return; setBusy(true); const choice = demoActions[context.session.scenario_id]?.[context.turn.turn_number - 1]; const result = await api<{ ok: boolean; failure_reason?: string; next_status?: string }>('/api/turn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ schema_version: '1.0', operation_id: `${context.seat.character_id}-${context.turn.turn_number}-${crypto.randomUUID()}`, expected_turn_id: context.turn.turn_id, expected_source_revision: context.turn.source_revision, actor_id: context.seat.character_id, asserted_outcomes: [], ...choice }) }); setNotice(result.ok ? (result.next_status === 'complete' ? 'The shared session reached its stopping point.' : 'The world resolved the turn. A new brief is ready.') : result.failure_reason || 'The turn could not be submitted.'); await refresh(); setBusy(false); }
  async function prepareScenario(scenarioId = selectedScenario) { setBusy(true); await api('/api/reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario_id: scenarioId }) }); setNotice('A fresh persistent table is ready.'); await refresh(); setBusy(false); }
  async function createHosted() { setBusy(true); const result = await api<{ ok: boolean; status?: string; failure_reason?: string }>('/api/v2/sessions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mode: hostedMode, webmcp_opt_in: webmcpOptIn, forge_prompt: forgePrompt }) }); setNotice(result.ok ? (hostedMode === 'quick_forge' ? 'Quick Forge started. The table will open after validation.' : 'Hosted jury campaign prepared.') : result.failure_reason || 'Hosted runtime is not configured yet.'); if (result.ok) { setHostedOpen(false); await refresh(); } setBusy(false); }
  async function submitHuman() { if (!context || !humanAction.trim() || !hosted) return; setBusy(true); const result = await api<{ ok: boolean; failure_reason?: string }>(`/api/v2/sessions/${encodeURIComponent(context.session.session_id)}/human-intents`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ operation_id: `human-${context.turn.turn_number}-${crypto.randomUUID()}`, action: humanAction }) }); setNotice(result.ok ? 'Your move entered the joint coordination window.' : result.failure_reason || 'Your move could not be submitted.'); if (result.ok) setHumanAction(''); setBusy(false); }
  async function primaryAction() { if (!active && !complete) return join(); if (complete) return prepareScenario(); if (hosted) return submitHuman(); return simulate(); }
  const primaryLabel = !active && !complete ? 'Take Your Seat' : complete ? 'Open a New Tale' : hosted ? 'Commit Move' : 'Resolve Demo Turn';

  return <main className="living-table" data-theme={theme}>
    <header className="topbar">
      <div className="brand-lockup"><span className="brand-mark" aria-hidden="true"><ShieldChevron weight="duotone" /></span><div><span>RePoG</span><strong>Living Table</strong></div></div>
      <label className="campaign-picker"><span>Campaign</span><select value={selectedScenario} onChange={(event) => { const next = event.target.value; setSelectedScenario(next); void prepareScenario(next); }} disabled={busy}><option value="black-gull">Prepared real campaign</option><option value="orison-signal">Orison signal test</option></select><CaretDown aria-hidden="true" /></label>
      <div className="topbar-actions"><span className={`connection-pill ${webmcp}`}><i aria-hidden="true" />{webmcp === 'ready' ? 'Agent bridge ready' : webmcp === 'unavailable' ? 'Browser without WebMCP' : 'Finding Agent Seat'}</span><button className={`quiet-button ${lens ? 'active' : ''}`} onClick={() => setLens((value) => !value)}><MagnifyingGlass weight="bold" />Designer Lens</button><button className="icon-button" aria-label="Open story ledger" onClick={() => document.getElementById('story-ledger')?.scrollIntoView({ behavior: 'smooth' })}><BookOpen weight="duotone" /></button><button className="icon-button" aria-label="Open table settings" onClick={() => setHostedOpen(true)}><GearSix weight="duotone" /></button><button className="hosted-button" onClick={() => setHostedOpen(true)}>Open Hosted Table</button></div>
    </header>

    <section className="table-stage" aria-label="Shared roleplaying table">
      <aside className="seat player-seat"><div className="portrait-frame"><img src={visual?.human_seat.portrait_url || '/assets/living-table/arden-portrait.png'} alt={visual?.human_seat.portrait_alt || 'The human player character'} /><span className="seat-online" aria-label="Human player connected" /></div><p className="seat-kicker">Human Player</p><h2>{visual?.human_seat.display_name || 'Arden'}</h2><span className="seat-role">{visual?.human_seat.role || 'Black Gull investigator'}</span><div className="fact-stack" aria-label="What your character perceives">{(context?.brief.perceivable_facts || []).slice(0, 3).map((fact, index) => { const Icon = factIcons[index] || Eye; return <div className="fact-card" key={fact}><Icon weight="duotone" aria-hidden="true" /><span>{fact}</span></div>; })}</div><div className="continuity-note"><span>Continuity</span><p>{latestConsequence || 'No prior result yet. Join once; the agent can continue across turns.'}</p></div></aside>
      <article className="scene" style={{ backgroundImage: `url(${visual?.scene_art.url || (theme === 'space_operatic' ? '/assets/living-table/orison-scene.png' : '/assets/living-table/black-gull-scene.png')})` }} aria-label={visual?.scene_art.alt || 'The active campaign scene'}><div className="scene-copy"><p>Persistent session · Turn {context?.turn.turn_number || 1}{context?.session.total_turns ? ` of ${context.session.total_turns}` : ''}</p><h1>{context?.turn.title || 'Preparing the table'}</h1><span>{context?.brief.summary || 'The world is gathering around the shared table.'}</span><em>{context?.brief.pressure || 'Every choice leaves a trace.'}</em></div><div className="turn-ribbon" aria-label="Turn coordination status"><strong>Turn {context?.turn.turn_number || 1}</strong><span>of {context?.session.total_turns || '∞'}</span><i aria-hidden="true" /><div><b>{active ? 'Joint turn coordination' : complete ? 'Session complete' : 'Seats awaiting players'}</b><small>{active ? '15 seconds to align your move.' : complete ? 'The table remembers every consequence.' : 'Take your seat to begin.'}</small></div><HourglassHigh weight="duotone" aria-hidden="true" /></div><div className="scene-state"><Compass weight="duotone" /><span>{context?.session.status || 'loading'}</span></div></article>
      <aside className="seat agent-seat"><div className="portrait-frame"><img src={visual?.agent_portrait.url || (theme === 'space_operatic' ? '/assets/living-table/iko-portrait.png' : '/assets/living-table/mira-portrait.png')} alt={visual?.agent_portrait.alt || 'The Agent Seat character'} /><span className="seat-online agent" aria-label="Agent Seat connected" /></div><p className="seat-kicker">Agent Seat</p><h2>{context?.seat.display_name || 'Mira'} <small>· {context?.seat.role || 'Companion'}</small></h2><div className="agent-status"><span><Check weight="bold" />{active ? `Ready for Turn ${context?.turn.turn_number || 1}` : context?.seat.status || 'Seat ready'}</span><span><UserCircle weight="duotone" />Seat: {context?.seat.status || 'ready'}</span><span><Feather weight="duotone" />Writes: Intent only</span></div><div className="nature"><span>{context?.seat.display_name || 'Agent'}&apos;s nature</span><p>{context?.seat.persona.prioritized_values || 'Protect the party while preserving independent judgment.'}</p><ul>{context?.seat.persona.decision_rules.slice(0, 3).map((rule) => <li key={rule}>{rule}</li>)}</ul></div></aside>
    </section>

    <section className="move-desk" aria-label="Commit a move"><div className="move-heading"><span className="round-icon"><Crosshair weight="duotone" /></span><div><h2>What is your move?</h2><p>{hosted ? 'Describe your intent. The Agent Seat may agree, adapt, or choose differently.' : 'Use WebMCP for the real Agent Seat, or resolve the prepared demo turn.'}</p></div></div><label className="move-input"><span className="sr-only">Describe your move</span><textarea value={humanAction} onChange={(event) => setHumanAction(event.target.value)} maxLength={240} rows={1} disabled={!hosted || !active} placeholder={hosted ? 'I want to…' : active ? 'The prepared Agent Seat is listening through WebMCP…' : 'Take your seat to begin…'} /><small>{humanAction.length}/240</small><Feather weight="duotone" aria-hidden="true" /></label><button className="commit-button" onClick={() => void primaryAction()} disabled={busy || (hosted && active && !humanAction.trim())}><span>{busy ? 'World turning…' : primaryLabel}</span><ShieldChevron weight="duotone" aria-hidden="true" /></button><p className="move-notice" role="status" aria-live="polite">{notice}</p></section>

    <section className="ledger" id="story-ledger"><div className="ledger-history"><h2>Story Ledger</h2><ol><li><span>Session start</span><p>The party arrives at {theme === 'space_operatic' ? 'Orison Station' : 'The Gilded Gull'}.</p></li>{context?.history.slice(-2).map((event) => <li key={event.sequence}><span>Turn {event.turn_number}</span><p>{event.summary}</p></li>)}</ol></div><div className="ledger-tabs"><div role="tablist" aria-label="Story ledger views"><button role="tab" aria-selected={ledgerTab === 'events'} onClick={() => setLedgerTab('events')}>Session Events</button><button role="tab" aria-selected={ledgerTab === 'thread'} onClick={() => setLedgerTab('thread')}>Thread</button></div>{ledgerTab === 'events' ? <div className="turn-list">{trace.map((item) => <div className={item.current ? 'current' : ''} key={item.label}><strong>{item.label}</strong><span>{item.done ? 'Resolved' : item.current ? 'In progress' : 'Queued'}</span>{item.current && <i aria-hidden="true" />}</div>)}</div> : <div className="thread-copy"><Sparkle weight="duotone" /><p>{latestConsequence || context?.brief.summary || 'The shared story will gather here as turns resolve.'}</p></div>}</div><div className="scene-record"><h2>The Scene</h2><p>{context?.brief.summary}</p><p>{context?.brief.perceivable_facts.join(' ')}</p></div></section>

    {lens && context && <section className="designer-lens" aria-label="Designer Lens"><div><h2>Shared table sees</h2><ul>{context.brief.party_public_facts.map((fact) => <li key={fact}>{fact}</li>)}</ul></div><div><h2>Bounded Agent Seat receives</h2><ul>{context.brief.relevant_knowledge.map((fact) => <li key={fact}>{fact}</li>)}</ul></div><div><h2>Runtime truth</h2><p>Revision {context.session.revision} · {context.session.resolver_mode} resolver · intent-only authority</p><button onClick={() => setLens(false)}>Close Designer Lens</button></div></section>}
    <footer className="table-footer"><span><ShieldChevron weight="duotone" />Campaign Tone <strong>{theme === 'space_operatic' ? 'Procedural · Orbital' : 'Fantasy · Noir'}</strong></span><span><Eye weight="duotone" />Table Safety <strong>Lines & Veils</strong></span><span><Compass weight="duotone" />Session <strong>Persistent</strong></span></footer>

    {hostedOpen && <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setHostedOpen(false); }}><section className="hosted-dialog" role="dialog" aria-modal="true" aria-labelledby="hosted-title"><button className="dialog-close" onClick={() => setHostedOpen(false)} aria-label="Close hosted table settings"><X weight="bold" /></button><p className="dialog-kicker">Jury-ready runtime</p><h2 id="hosted-title">Open a hosted Living Table</h2><p>The campaign remains live without your computer. Human and Agent Seats meet on this same page.</p><label>Campaign source<select value={hostedMode} onChange={(event) => setHostedMode(event.target.value as 'prepared' | 'quick_forge')}><option value="prepared">Prepared real campaign</option><option value="quick_forge">Quick Forge a new world</option></select></label>{hostedMode === 'quick_forge' && <><label>World seed<textarea value={forgePrompt} onChange={(event) => setForgePrompt(event.target.value)} maxLength={2000} rows={4} /></label><label className="check-row"><input type="checkbox" checked={webmcpOptIn} onChange={(event) => setWebmcpOptIn(event.target.checked)} />Enable one Tier 3 companion as an Agent Seat</label></>}<button className="dialog-primary" onClick={() => void createHosted()} disabled={busy || (hostedMode === 'quick_forge' && !webmcpOptIn)}>{busy ? 'Opening table…' : 'Open Hosted Table'}</button></section></div>}
  </main>;
}
