export type ToolDefinition = {
  name: string;
  title: string;
  description: string;
  inputSchema: Record<string, unknown>;
  annotations: { readOnlyHint: boolean; untrustedContentHint: boolean };
  execute: (input: Record<string, unknown>, options?: { signal?: AbortSignal }) => Promise<unknown>;
};

type Api = <T>(url: string, options?: RequestInit) => Promise<T>;
type KnowledgeContext = { brief: { knowledge_index: Array<{ fact_id: string; text: string; status: string; source: string; confidence: number }> }; turn: { source_revision: number } };

export function createWebMcpTools(api: Api, refresh: () => Promise<unknown>): ToolDefinition[] {
  const reads = { readOnlyHint: true, untrustedContentHint: true };
  const writes = { readOnlyHint: false, untrustedContentHint: true };
  return [
    { name: 'repog.join_session', title: 'Join the RePoG Agent Seat', description: 'Bind to the prepared character. Then autonomously repeat get_next_turn, commit_intent, and get_intent_status until a stop condition is returned. Do not ask the human between ordinary turns.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: writes, execute: async (_input, options) => { const result = await api('/api/session', { method: 'POST', signal: options?.signal }); await refresh(); return result; } },
    { name: 'repog.get_next_turn', title: 'Get the next RePoG turn', description: 'Read the durable session and bounded character brief. When ready, play only the active character from the supplied values, knowledge, continuity, capabilities, and authority.', inputSchema: { type: 'object', properties: { after_revision: { type: 'integer', minimum: 0 } }, additionalProperties: false }, annotations: reads, execute: async (input, options) => api(`/api/next${Number.isInteger(input.after_revision) ? `?after_revision=${input.after_revision}` : ''}`, { signal: options?.signal }) },
    { name: 'repog.recall_knowledge', title: 'Recall bounded character knowledge', description: 'Search only the active character’s epistemic projection and return provenance—not GM truth or another character’s private state.', inputSchema: { type: 'object', properties: { topic: { type: 'string', maxLength: 120 }, limit: { type: 'integer', minimum: 1, maximum: 12 } }, required: ['topic'], additionalProperties: false }, annotations: reads, execute: async (input, options) => { const current = await api<KnowledgeContext>('/api/context', { signal: options?.signal }); const topic = String(input.topic || '').toLocaleLowerCase(); const facts = current.brief.knowledge_index.filter((fact) => fact.text.toLocaleLowerCase().includes(topic) || fact.fact_id.includes(topic)).slice(0, Number(input.limit) || 8); return { ok: true, topic: input.topic, facts, source_revision: current.turn.source_revision }; } },
    { name: 'repog.commit_intent', title: 'Commit a character intent', description: 'Submit a structured proposal for the active character. RePoG—not the agent—resolves all world outcomes. asserted_outcomes must be empty.', inputSchema: { type: 'object', properties: { schema_version: { type: 'string', const: '1.0' }, operation_id: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' }, expected_turn_id: { type: 'string', minLength: 1, maxLength: 180 }, expected_source_revision: { type: 'integer', minimum: 0 }, actor_id: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' }, action_type: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' }, action: { type: 'string', minLength: 1, maxLength: 1200 }, approach: { type: 'string', maxLength: 600 }, speech: { type: 'string', maxLength: 1200 }, targets: { type: 'array', items: { type: 'string' }, maxItems: 16 }, resource_refs: { type: 'array', items: { type: 'string' }, maxItems: 16 }, knowledge_refs: { type: 'array', items: { type: 'string' }, maxItems: 16 }, requested_effect: { type: 'string', maxLength: 500 }, asserted_outcomes: { type: 'array', maxItems: 0 } }, required: ['schema_version', 'operation_id', 'expected_turn_id', 'expected_source_revision', 'actor_id', 'action_type', 'action', 'targets', 'resource_refs', 'knowledge_refs', 'requested_effect', 'asserted_outcomes'], additionalProperties: false }, annotations: writes, execute: async (input, options) => { const result = await api('/api/turn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input), signal: options?.signal }); await refresh(); return result; } },
    { name: 'repog.get_intent_status', title: 'Get intent status', description: 'Read only character-visible status and consequences for a committed operation.', inputSchema: { type: 'object', properties: { operation_id: { type: 'string', pattern: '^[a-z0-9][a-z0-9._-]{0,63}$' } }, required: ['operation_id'], additionalProperties: false }, annotations: reads, execute: async (input, options) => api(`/api/status?operation_id=${encodeURIComponent(String(input.operation_id))}`, { signal: options?.signal }) },
    { name: 'repog.pause_session', title: 'Pause the RePoG session', description: 'Pause without resetting history. A later join resumes the same revision.', inputSchema: { type: 'object', properties: { expected_session_revision: { type: 'integer', minimum: 0 } }, required: ['expected_session_revision'], additionalProperties: false }, annotations: writes, execute: async (input, options) => { const result = await api('/api/pause', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input), signal: options?.signal }); await refresh(); return result; } },
  ];
}
